/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.WeatherStationBL;
import BL.myTableCellRenderer;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author johannesriedmueller
 */
public class WeatherStationGUI extends javax.swing.JFrame {

    private WeatherStationBL bl = new WeatherStationBL();
    private myTableCellRenderer tcr = new myTableCellRenderer();

    public WeatherStationGUI() {
        initComponents();
        taAll.setModel(bl);
        taAll.setDefaultRenderer(Object.class, tcr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm1 = new javax.swing.JPopupMenu();
        miHideSeaLevel = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAll = new javax.swing.JTable();
        mbTop = new javax.swing.JMenuBar();
        meStations = new javax.swing.JMenu();
        miAdd = new javax.swing.JMenuItem();
        miRemove = new javax.swing.JMenuItem();
        meValues = new javax.swing.JMenu();
        miSetTemp = new javax.swing.JMenuItem();
        miSetHumidity = new javax.swing.JMenuItem();
        meFile = new javax.swing.JMenu();
        miSave = new javax.swing.JMenuItem();

        miHideSeaLevel.setText("Hide/Show Sea Level");
        miHideSeaLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHideSeaLevelActionPerformed(evt);
            }
        });
        pm1.add(miHideSeaLevel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        taAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taAll.setComponentPopupMenu(pm1);
        jScrollPane1.setViewportView(taAll);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        meStations.setText("Stations");

        miAdd.setText("Add Weather Satation");
        miAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddActionPerformed(evt);
            }
        });
        meStations.add(miAdd);

        miRemove.setText("Remoev Weather Station");
        miRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemoveActionPerformed(evt);
            }
        });
        meStations.add(miRemove);

        mbTop.add(meStations);

        meValues.setText("Values");

        miSetTemp.setText("Set Temperature");
        miSetTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSetTempActionPerformed(evt);
            }
        });
        meValues.add(miSetTemp);

        miSetHumidity.setText("Set Humidity");
        miSetHumidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSetHumidityActionPerformed(evt);
            }
        });
        meValues.add(miSetHumidity);

        mbTop.add(meValues);

        meFile.setText("File");

        miSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.META_MASK));
        miSave.setText("save");
        miSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveActionPerformed(evt);
            }
        });
        meFile.add(miSave);

        mbTop.add(meFile);

        setJMenuBar(mbTop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddActionPerformed
        WeatherStationDialog wsDialog = new WeatherStationDialog(this, true);
        wsDialog.setVisible(true);
        if (wsDialog.isOk()) {
            bl.add(wsDialog.getWeatherStation());
        }
    }//GEN-LAST:event_miAddActionPerformed

    private void miRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemoveActionPerformed
        switch (taAll.getSelectedRowCount()) {
            case 0:
                JOptionPane.showMessageDialog(null, "You didn't select an item.");
                break;
            case 1:
                bl.remove(taAll.getSelectedRow());
                break;
            default:
                bl.remove(taAll.getSelectedRows());
        }
    }//GEN-LAST:event_miRemoveActionPerformed

    private void miSetTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSetTempActionPerformed
        if (taAll.getSelectedRowCount() == 1) {
            try {
                bl.setTemperature(taAll.getSelectedRow(), Double.parseDouble(JOptionPane.showInputDialog("Please enter the new value for the temperature:")));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select ONE item!");
        }
    }//GEN-LAST:event_miSetTempActionPerformed

    private void miSetHumidityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSetHumidityActionPerformed
        if (taAll.getSelectedRowCount() == 1) {
            try {
                bl.setHumidity(taAll.getSelectedRow(), Integer.parseInt(JOptionPane.showInputDialog("Please enter the new value for the temperature:")));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select ONE item!");
        }
    }//GEN-LAST:event_miSetHumidityActionPerformed

    private void miHideSeaLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHideSeaLevelActionPerformed
        bl.hideShowSeaLevel();
        tcr.setHidden();
    }//GEN-LAST:event_miHideSeaLevelActionPerformed

    private void miSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveActionPerformed
        try {
            bl.save(new File("./savedStations.ser"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error with file :(");
        }
    }//GEN-LAST:event_miSaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            bl.load(new File("./savedStations.ser"));
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error with file :(");
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherStationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherStationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherStationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherStationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherStationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mbTop;
    private javax.swing.JMenu meFile;
    private javax.swing.JMenu meStations;
    private javax.swing.JMenu meValues;
    private javax.swing.JMenuItem miAdd;
    private javax.swing.JMenuItem miHideSeaLevel;
    private javax.swing.JMenuItem miRemove;
    private javax.swing.JMenuItem miSave;
    private javax.swing.JMenuItem miSetHumidity;
    private javax.swing.JMenuItem miSetTemp;
    private javax.swing.JPopupMenu pm1;
    private javax.swing.JTable taAll;
    // End of variables declaration//GEN-END:variables
}
